### PR TITLE
Update depedencies to support new cockpit build system

### PR DESCRIPTION
**Pull request by Nykseli**
Since cockpit has updated the way applications are build, `cockpit-wicked` needs to be updated to support this.

This PR aims to add support for the new build system and update old dependencies too.
This PR also adds support for cockpit's dark theme since it was a trivial change.

After this gets merged, the package can get updated in OBS and get accepted to openSUSE:Factory, and other relevant projects.

I've created a test package that can be used as a template: 
https://build.opensuse.org/package/show/home:malikirri/cockpit-wicked-playground

### CODE REVIEW

**Comment by imobachgs** [comment]
Hi @Nykseli. Thanks for the PR!

However, I have a question: would this new way of building Cockpit modules work in SLE 15 SP6 too? Because that's the main target of cockpit-wicked.

**Comment by Nykseli** [comment]
It looks like the cockpit version in SLE 15 is too old for this. So these changed would break it.
If SLE 15 is the main target, I can just add these commits as patches in OBS!

**Comment by imobachgs** [comment]
> It looks like the cockpit version in SLE 15 is too old for this. So these changed would break it. If SLE 15 is the main target, I can just add these commits as patches in OBS!

Well, perhaps we could use a separate branch in the repository for SLE-15 versions so you do not need to put all that stuff in OBS.

**Comment by Nykseli** [comment]
> Well, perhaps we could use a separate branch in the repository for SLE-15 versions so you do not need to put all that stuff in OBS.

I like that solution too. Makes maintaining the OBS package a lot easier. :slightly_smiling_face:

**Comment by Nykseli** [comment]
Hi!

What is the status of this PR? Is there something I can do to help move things along? :slightly_smiling_face:

**Comment by imobachgs** [comment]
I am sorry. I will review and hopefully merge it tomorrow.

**Review by imobachgs — APPROVED** [review]

**Comment by imobachgs** [comment]
Hi @Nykseli, thanks a lot for your effort. The PR looks fine, so I am merging it. I have created a `SLE-15` branch to release new versions for SLE-15 based products and I will update our internal documentation.

**Pull request merged**
