### PR TITLE
Move excluded errors handling to wicked client

### PR DESCRIPTION
**Pull request by dgdavid**

### CODE REVIEW

**Review by imobachgs — COMMENTED** [review]
At first sight, it looks good. What else is missing?

**Comment by dgdavid** [comment]
> At first sight, it looks good. What else is missing?

Testing. I'd like to have a short talk about them. And I also wanted to evaluate if the other methods (e.g., getInterfaces) should rely in runCommand (which make the return value slightly different)

**Comment by imobachgs** [comment]
OK, I see. I have done some testing and came to the conclusion that we should remove code 162 from the list of excluded codes.

**Comment by imobachgs** [comment]
Regarding the `getInterfaces`, please, do not change them at this point. We can discuss about it after the release.

**Comment by dgdavid** [comment]
> OK, I see. I have done some testing and came to the conclusion that we should remove code 162 from the list of excluded codes.

Done

**Review by teclator — APPROVED** [review]
LGTM

**Pull request merged**
